# Java context path
server.servlet.context-path: /java

# URL to node app
app.node.url: http://172.17.0.1:8081/

spring:
  jpa:
    properties.hibernate:
      temp.use_jdbc_metadata_defaults: false

  datasource:
    url: jdbc:postgresql://172.17.0.1:5432/demodb
    username: demouser
    password: DemoPa$$